### PR TITLE
Microbenchmarking tool changed color output to csv output 

### LINKED ISSUE #194: microbenchmarking tool should output CSV
Currently it outputs color-coded output which might be a bit nice, but it would be better to have it output CSV so that it can be help generate performance and regression graphs.

### PR DESCRIPTION
**Pull request by gtsoul-tech**
changed color output to csv output(clang formatted)
Closes: #194

### CODE REVIEW

**Comment by gtsoul-tech** [comment]
microbenchmarking tool changed color output to csv output (kept color output in comments)

File: benchmarks/benchmarks.cpp [hunk 1]
```diff
@@ -122,117 +125,125 @@ static void run_benchmarks(int size, int loops, int max_matches, bool is_reverse
...
+int main() {
     int matches[] = {0, MAX_MATCHES};
     std::vector<size_t> sizes;
-    for (size_t i = 0; i < N; i++) sizes.push_back(16000 << i*2);
-    const char charset[] = "aAaAaAaAAAaaaaAAAAaaaaAAAAAAaaaAAaaa"; 
-  
+    for (size_t i = 0; i < N; i++)
+        sizes.push_back(16000 << i * 2);
+    const char charset[] = "aAaAaAaAAAaaaaAAAAaaaaAAAAAAaaaAAaaa";
+    printf("Bench Label, max_matches, size,loops, total_sec, avg_time, "
```
Comment (markos) [inline benchmarks/benchmarks.cpp]: Could you replace "Bench Label" with "Matcher" instead?

**Review by markos — APPROVED** [review]
LGTM, approved
